// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwYwzipNl40Kbx7lrTQjb26L9MhaO0ZYk',
    appId: '1:153285982980:web:4e7cfe469cbfab55d9ee51',
    messagingSenderId: '153285982980',
    projectId: 'deu-mppt-logging',
    authDomain: 'deu-mppt-logging.firebaseapp.com',
    databaseURL: 'https://deu-mppt-logging-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'deu-mppt-logging.appspot.com',
    measurementId: 'G-5F6W2TM2SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9QQx-z4LX8p2A4jc60rgkB-_4tnGJ0UA',
    appId: '1:153285982980:android:20f1d05a2d934218d9ee51',
    messagingSenderId: '153285982980',
    projectId: 'deu-mppt-logging',
    databaseURL: 'https://deu-mppt-logging-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'deu-mppt-logging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMrNUcpeeGBvMvJD3O8saoFezTVnhrUPQ',
    appId: '1:153285982980:ios:655ff8450ba14ed8d9ee51',
    messagingSenderId: '153285982980',
    projectId: 'deu-mppt-logging',
    databaseURL: 'https://deu-mppt-logging-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'deu-mppt-logging.appspot.com',
    iosBundleId: 'com.example.deulog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMrNUcpeeGBvMvJD3O8saoFezTVnhrUPQ',
    appId: '1:153285982980:ios:237228f2bf24b088d9ee51',
    messagingSenderId: '153285982980',
    projectId: 'deu-mppt-logging',
    databaseURL: 'https://deu-mppt-logging-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'deu-mppt-logging.appspot.com',
    iosBundleId: 'com.example.deulog.RunnerTests',
  );
}
